export type RoastRecord = {
  id: string;
  created_at: string;
  roast_date: string;
  bean_name: string;
  origin: string;
  process: string;
  variety: string;
  roast_level: string;
  other_info?: string;
  // 焙煎前
  charge_weight: number;
  charge_temp: number;
  target_roast_level: string;
  // 焙煎後・工程
  charge_time: string;
  dry_end: string;
  yellow_start: string;
  maillard_start: string;
  first_crack: string;
  first_crack_peak: string;
  second_crack: string;
  drop_time: string;
  total_time: string;
  drop_temp: number;
  after_weight: number;
  color: number;
  // テイスティング
  acidity: number;
  sweetness: number;
  richness: number;
  body: number;
  balance: number;
  cleanliness: number;
  aftertaste: number;
  total_score: number;
  aroma_powder: number;
  aroma_powder_note?: string;
  aroma_liquid: number;
  aroma_liquid_note?: string;
  flavor: number;
  flavor_note?: string;
  strength: number;
  uniformity: number;
  cleanness: number;
  // 総合評価
  overall_total_score: number;
  personal_score: number;
  issues?: string;
  summary?: string;
}; 